### ISSUE TITLE
Problems when saving special characters

### ISSUE THREAD

**Issue by mblabs** [vlad-ghita/sections_event#10]
When I try to insert special characters in my input field like (" or ') the characters are non stored in the DB.
1. Symphony core event saves correctly special characters 
2. Symphony backend saves correctly special characters 

then I believe is an issue of the section event

**Comment by vlad-ghita** [comment]
Double quotes & single quotes? Very odd. I didn't have any issues with this one. Can you provide an example form?

**Comment by mblabs** [comment]
`<form class="form-admin" enctype="multipart/form-data" action="" method="post">
<input type="hidden" value="5242880" name="MAX_FILE_SIZE">
<input name="sections[articles][title]" type="text" required="required" autocomplete="off"/>
<input name="action[sections]" type="submit" value="submit" class="button" />
</form>`

Text in input : "Test"

Result in debug:

`````` <events>
        <sections>
          <articles>
                <entry position="0">
                    <post-values>
                        title>\&quot;Test\&quot;</title>
 </post-values>
                    <rep-post-values>
<title>Test</title>```


The informations are stored, but not double quotes & single quotes.
``````

**Comment by mblabs** [comment]
@vlad-ghita I believe the PHP configuration of my server causes the escaping of quotes. I think I can solve using the stripslashes, but I've no idea where is the line where the fields are processed. Can you help me?

**Comment by vlad-ghita** [comment]
Insert [here](https://github.com/vlad-ghita/sections_event/blob/master/events/event.sections.php#L294) whatever you need.

`$original_fields` is an array with information for one entry. Apply your code on that variable. Make sure you make it recursive because the array can be deeper than one level.

**Comment by mblabs** [comment]
Thanks Vlad! Now it works like a charm!

I've modified the line

$fields = $original_fields;

in

$fields = json_decode(stripslashes(json_encode($original_fields)), true);

**Comment by vlad-ghita** [comment]
Great!
