### ISSUE TITLE
Different filters on different sections?

### ISSUE THREAD

**Issue by patrickyan** [vlad-ghita/sections_event#12]
So I’ve got something like this:

```
        $_REQUEST['sections']['reservations']['__filters'] = array(
            'Balanced_Debit-create'
        );
        $_REQUEST['sections']['users']['__filters'] = array(
            'Balanced_Customer-create-addBankAccount'
        );
```

But only the filters of the last section are run. Is this a problem with Sections Event or my filter? Here are my filters for your reference: https://github.com/patrickyan/balanced/blob/master/extension.driver.php#L152

**Comment by patrickyan** [comment]
I’m guessing it should work, because the `SE-PreareFilter` delegate is called per entry? https://github.com/vlad-ghita/sections_event/blob/141b8bbac46f7905546a5eb044896b47588baea6/events/event.sections.php#L217

**Comment by vlad-ghita** [comment]
That delegate is fired per entry basis. It should take everything into account.

Insert

```
print_r($sections_prepare);die;
```

 at line 86, after

```
$sections_prepare = $this->sectionsPrepare( $sections_input );
```

Paste the result here (or private pastie if it's too large).

**Comment by patrickyan** [comment]
To be more specific on the error: in the event XML, both sections show the same post data (generated by the last filter on the users section).

**Comment by patrickyan** [comment]
I just tried with different filters (ETM), and it seems to work. I’m guessing it’s my implementation of the `SE_PrepareFilter` delegate.

I think it’s because I have the filter to only run if the session is not set https://github.com/patrickyan/balanced/blob/master/extension.driver.php#L111

The session is unset after saving the entry.

I’m guessing Sections Event runs all the `SE_PrepareFilter` before running the `SE_CommitFilter`. I guess I need to remove this behavior.

**Comment by vlad-ghita** [comment]
> I’m guessing Sections Event runs all the `SE_PrepareFilter` before running the `SE_CommitFilter`. I guess I need to remove this behavior.

Yes indeed.
