### ISSUE TITLE
Mutliple sections and Reflection Field

### ISSUE THREAD

**Issue by patrickyan** [vlad-ghita/sections_event#13]
What I’m trying to do is create a sort parameter like `101`, where 1 and 0 are yes/no for certain fields. My problem is that one of the fields I’m checking is a SBL. I’m guessing sections event saves the linked section, then goes back to add the linked entries, but doesn’t resave with the reflection field.

Example:

```
order: published (checkbox), images attached (sbl), gender (select box)
```

Expecting

```
111
```

Getting

```
101
```

**Comment by vlad-ghita** [comment]
This should work, no problem. On [these](https://github.com/vlad-ghita/sections_event/blob/master/events/event.sections.php#L125-L136) lines, replace IDs in SBLs and only then commit entries. Sections Event [updates](https://github.com/vlad-ghita/sections_event/blob/master/extension.driver.php#L163) Reflection fields.

Is this a bug in latest version?

**Comment by patrickyan** [comment]
Yes, as far as I can tell the reflections aren't being updated after SBL (need to go back and save again)

**Comment by patrickyan** [comment]
It also looks like editing entries does not force reflection fields to update.

**Comment by vlad-ghita** [comment]
Aaaaa, I know this! :)

In order to be updated, the Reflection field needs to be triggered, included in the form.

In your case, the Reflection (`settings` or what's the name) uses `published`, `images attached` and `gender`. Make sure that whenever you change any of these, you include the Reflection as well.

```
<input name="sections[orders][settings]" value="" type="hidden"/>
```

Another thing on Reflection. Even if you update the value for one used field, do supply the values for all used fields because `settings` needs the values from all three in order to process correctly.

**Comment by patrickyan** [comment]
That fixed the problem with editing entries!

But the problem with SBL linked entries still exists. Reflection still seems to be running _before_ the SBL field is updated.

**Comment by vlad-ghita** [comment]
So, if you supply a form with these values:

```
<input name="sections[orders][settings]" value="" type="hidden"/>
<input name="sections[orders][published]" value="yes" type="hidden"/>
<input name="sections[orders][images][]" value="483" type="hidden"/>
<input name="sections[orders][images][]" value="297" type="hidden"/>
<input name="sections[orders][gender]" value="Male" type="hidden"/>
```

You say that `settings` will have incorrect values?

Please supply a _working_ example of your use case and a _not working_ example (in the same fashion above).

**Comment by vlad-ghita** [comment]
K. I found the problem. A fix is on the way.

**Comment by vlad-ghita** [comment]
Fixed in [this](https://github.com/vlad-ghita/sections_event/commit/c86c289f0ebf94ae538d98fc89976a03523c636b) commit.

The order in which sections are executed is important for Entries with Reflection field.

In your case, you have an `Images` section and an `Orders` section (don't know the name, using this one). Since the Reflection field in `Orders` section uses the SBL field that points to `Images` section, `Images` must be saved first, and then the `Order`, so Order Entry has titles from Images.

In your form, use the `__order` key to specify the order of sections:

```
<input name="sections[__order]" type="hidden" value="images,orders" />
```

**Comment by patrickyan** [comment]
Thanks so much, Vlad. Sorry that I’m so slow! Will try this out today :)

**Comment by patrickyan** [comment]
Unfortunately, it doesn’t seem like this works. (I used that exact input.) To be specific, the reflection field is being updated correctly when entries are _edited_. However, when new entries are _created_, the SBL field is still ignored.

**Comment by vlad-ghita** [comment]
:| weird. It's working fine for me. I was in same situation yesterday and the patch fixed it ...

What are the names of your sections? `Images` and `...` ?

**Comment by patrickyan** [comment]
It’s `images` and `listings`. In `listings`, the reflection field is called `sort-key` and the SBL is called `images`. `sort-key` is only getting the right SBL values after editing through front end with sections_event OR resaved through the Symphony admin.

**Comment by vlad-ghita** [comment]
So if you send this in the form it still doesn't work?

```
<input name="sections[__order]" type="hidden" value="images,listings" />
```

What's the result from `print_r($sections_input)` on [line 82](https://github.com/vlad-ghita/sections_event/blob/master/events/event.sections.php#L82)?

What's the result from `print_r($_REQUEST)` as well?

Let's make sure the order is correct.

**Comment by patrickyan** [comment]
`$sections_input` @ line 82

[redacted]

**Comment by vlad-ghita** [comment]
Well, hello problem. It seems the order isn't computed as it should.

Please replace [these lines](https://github.com/vlad-ghita/sections_event/blob/master/events/event.sections.php#L77-L81) with these: 

```
print_r($sections_input);

$order = null;
if( isset($sections_input['__order']) && is_string($sections_input['__order']) ){
    $order = array_filter(explode(',', $sections_input['__order']));
    unset($sections_input['__order']);
}

if( is_array($order) ){
    $sections_input = array_merge(array_flip($order), $sections_input);
}

print_r($sections_input);die;
```

And show me the output.

Thanks.

**Comment by patrickyan** [comment]
Here you go

[redacted]

**Comment by patrickyan** [comment]
This may also be related, but the reflection field doesn’t update correctly. I have a field that calculates a duration from the date/time field and then multiplies by a number field. When editing entries (changing the number and dates), the reflection field changes based on the new number but not the duration.

**Comment by patrickyan** [comment]
(Saving in the Symphony admin works perfectly.)

**Comment by vlad-ghita** [comment]
You can safely remove the `print_r(...)` instructions from my [previous comment](https://github.com/vlad-ghita/sections_event/issues/13#issuecomment-30847652).

Everything seems to be fine, from Sections Event point of view. The order of of keys in processed array is `images`, `listings`, which is correct.

I think there is another issue here. I recommend you debug this step by step and see where the other problem is.

**Comment by patrickyan** [comment]
@vlad-ghita - It works now, but it’s because your previous comment also changed the code. I’m guessing it’s the `array_flip($order)`. Can you commit this change to the repo?

![screen shot 2013-12-25 at 8 51 50 am](https://f.cloud.github.com/assets/858647/1808864/e274ad88-6d84-11e3-9516-340072eee211.png)

**Comment by vlad-ghita** [comment]
Yeah, I wanted to commit it, but was waiting for positive feedback :)

**Comment by patrickyan** [comment]
Awesome!
