### ISSUE TITLE
Sections Event and latest members not working

### ISSUE THREAD

**Issue by andrewminton** [vlad-ghita/sections_event#14]
There seems to be an issue using latest members release and Sections Event. I think it's related to the new feature in members where we can use multiple sections with members in v1.3

Is this a known bug?

**Comment by vlad-ghita** [comment]
What exactly isn't working?

**Comment by andrewminton** [comment]
When attempting to load the Section Permissions page of the initially installed Public role for this extension. I get the following error:

```
Symphony Fatal Error: There are multiple Member sections in this installation, please refer to the     README.

An error occurred in C:\wamp\www\site\extensions\members\extension.driver.php around line 596`
```

**Comment by vlad-ghita** [comment]
Aaa, that one. This is not compatible with Members 1.3, yet.

**Comment by andrewminton** [comment]
Coolio.

I just pulled main repos from Git so will checkout different branch. Please
close issue if you want to.
