### ISSUE TITLE
Unable to get multiple ids in a SBL field

### ISSUE THREAD

**Issue by patrickyan** [vlad-ghita/sections_event#3]
Sample code:

```
<input name="sections[images][0][image]" id="sections_images_0_image" type="file">
<input name="sections[images][1][image]" id="sections_images_1_image" type="file">
<input name="sections[listings][images][]" id="sections_listings_images" type="hidden" value="%images[0][system:id]%,%images[1][system:id]%">
```

Only the first (0) item is being included in the SBL field called `images`.

**Comment by patrickyan** [comment]
To be clear both image entries are created, but only the first id gets passed through to the hidden input.

**Comment by vlad-ghita** [comment]
Given this HTML

```
<input name="images[]" value="v1,v2,v3"/>
```

in PHP you will get an array called `images` and the element with first index `0` will contain the data:

```
$_POST['images'][0] === 'v1,v2,v3'
```

Given this data, SBL field will store only `v1`. (see [this](https://github.com/symphonycms/selectbox_link_field/blob/master/fields/field.selectbox_link.php#L488) line)

Given you want to link multiple entries, you have to pass them as elements of the array:

```
$_POST['images'][0] ==== 'v1'
$_POST['images'][1] ==== 'v2'
$_POST['images'][2] ==== 'v3'
```

So in HTML you will need something like this:

```
<input name="images[]" value="v1"/>
<input name="images[]" value="v2"/>
<input name="images[]" value="v3"/>
```

Applied to your example, you will need

```
<input name="sections[listings][images][]" type="hidden" value="%images[0][system:id]%"/>
<input name="sections[listings][images][]" type="hidden" value="%images[1][system:id]%"/>
```

=> in PHP

```
$_POST[listings][images][0] === %images[0][system:id]%
$_POST[listings][images][1] === %images[1][system:id]%
```

**Comment by patrickyan** [comment]
Sorry, I posted the wrong code. I'm actually using: 

```
<input name="sections[images][0][image]" id="sections_images_0_image" type="file">
<input name="sections[images][1][image]" id="sections_images_1_image" type="file">
<input name="sections[listings][images]" id="sections_listings_images" type="hidden" value="%images[0][system:id]%,%images[1][system:id]%">
```

I'm not trying to pass an array for multiple `listings` entries. I am creating one `listings` entry with many `images`. Basically it should be the same as the Readme's Example 4 (books and authors):

My SBL has multiple selection enabled, so it should receive the IDs of both image entries, but something is not going through.

**Comment by patrickyan** [comment]
Ah ok, I got it. So the behavior of SBL for multiple selections is to pass an array, not a comma separated list. 

I got confused by Example 4. Assuming Example 4 is passing the IDs to a SBL and not a text field, then shouldn't it also be passing an array of values?

**Comment by vlad-ghita** [comment]
> So the behavior of SBL for multiple selections is to pass an array, not a comma separated list. 

Yep.

> I got confused by Example 4. Assuming Example 4 is passing the IDs to a SBL and not a text field, then shouldn't it also be passing an array of values?

You are right. Thanks. Fixed it in [this](https://github.com/vlad-ghita/sections_event/commit/ddf29c7bf95a576966297a9e55d37ca65599bc97) commit.
